trigger:
- develop

variables:
- group: jfrog-artifactory

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      BUILD_CONFIGURATION: Debug
      MULTITHREADING: False
    mac:
      imageName: 'macos-10.13'
      BUILD_CONFIGURATION: Debug
      MULTITHREADING: False
    windows:
      imageName: 'vs2017-win2016'
      BUILD_CONFIGURATION: Debug
      MULTITHREADING: False
      BUILD_ARCH: x86_64
      VSINSTALL: "Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build"
      MSVC_PLATFORM: amd64

pool:
  vmImage: $(imageName)


steps:
- powershell: gci env:* | sort-object name

- bash: |
    mkdir -p $HOME/.inaos/cmake
    mkdir -p $HOME/INAOS
    repos="INAC_REPOSITORY_LOCAL=$HOME/INAOS\nINAC_REPOSITORY_REMOTE=https://inaos.jfrog.io/inaos/libs-release-local/inaos\nINAC_REPOSITORY_USRPWD=licensed:AKCp5bBraH7CasbsYCURsjzkbjXwVwdYcT7u39EiuL6GjnK1VKfKQWCd1E2E64mHokU5YUHku"
    echo $repos > $HOME/.inaos/cmake/repository.txt 
    git submodule update --init --recursive

- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  displayName: Add conda to PATH

- script: |
    conda install -y -c intel mkl-include=2019.3
    conda install -y -c intel mkl-static=2019.3
  env:
    jfrog_artifactory_uid: $(jfrog_artifactory_uid)
    jfrog_artifactory_pwd: $(jfrog_artifactory_pwd)
    
- script: |
    call "C:\Program Files (x86)\%VSINSTALL%\vcvarsall.bat" %MSVC_PLATFORM%
    mkdir cmake-build-%BUILD_CONFIGURATION%
    cd cmake-build-%BUILD_CONFIGURATION%
    cmake -G "NMake Makefiles" ../ -DCMAKE_BUILD_TYPE=%BUILD_CONFIGURATION%  -DMULTITHREADING=%MULTITHREADING% -DINAC_TARGET_ARCH=%BUILD_ARCH%
    nmake
  env:
    BUILD_CONFIGURATION: $(BUILD_CONFIGURATION)
    BUILD_ARCH: $(BUILD_ARCH)

- script: |
   @echo on
   cd cmake-build-%BUILD_CONFIGURATION%
   tests
  displayName: Execute tests

- script: |
   @echo on
   cd cmake-build-%BUILD_CONFIGURATION%
   call "C:\Program Files\CMake\bin\cpack.exe" -V
  displayName: Create package
