trigger: none

variables:
- group: jfrog-artifactory

jobs:
- job: BuildWindows
  
  strategy:
    matrix:
      windows:
        imageName: 'vs2017-win2016'
        BUILD_CONFIGURATION: Debug
        VSINSTALL: "Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build"
        MSVC_PLATFORM: amd64

  pool:
    vmImage: $(imageName)
  
  timeoutInMinutes: 0
  
  steps:
  - powershell: gci env:* | sort-object name
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH
  - script: |
      choco source add -n "inaos" -s "https://inaos.jfrog.io/inaos/api/nuget/nuget-release-local/" -u %jfrog_artifactory_uid% -p %jfrog_artifactory_pwd%
      choco install inaos-dev-quality-tools -y --force
      conda install -y -c intel mkl-include
      conda install -y -c intel mkl-static
      call "C:\Program Files (x86)\%VSINSTALL%\vcvarsall.bat" %MSVC_PLATFORM%
    env:
      BUILD_CONFIGURATION: $(BUILD_CONFIGURATION)
      VSINSTALL: $(VSINSTALL)
      MSVC_PLATFORM: $(MSVC_PLATFORM)
      jfrog_artifactory_uid: $(jfrog_artifactory_uid)
      jfrog_artifactory_pwd: $(jfrog_artifactory_pwd)
  - powershell: |
      mkdir -p $HOME/.inaos/cmake
      $inac_home = Join-Path -Path $HOME -ChildPath "INAOS"
      mkdir -p $inac_home
      $repos = "INAC_REPOSITORY_LOCAL=$inac_home`nINAC_REPOSITORY_REMOTE=https://inaos.jfrog.io/inaos/libs-release-local/inaos`nINAC_REPOSITORY_USRPWD=licensed:AKCp5bBraH7CasbsYCURsjzkbjXwVwdYcT7u39EiuL6GjnK1VKfKQWCd1E2E64mHokU5YUHku"
      Set-Content $HOME/.inaos/cmake/repository.txt $repos
      $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
      $fileContent += $env:gitlab_priv_key.Replace(' ', "`n")
      $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
      Set-Content $HOME/.ssh/id_rsa $fileContent  
      
      
