
pool:
  vmImage: 'vs2017-win2016'


steps:
- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(System.DefaultWorkingDirectory)'
    feedsToUse: 'internal'
    vstsFeed: '91c218bd-84d1-4796-85e7-b9adfd3d51ac/3eedad50-ec7f-4115-8ba9-09bbcc76f8f5'
    vstsFeedPackage: 'llvm-windows_vs17-x86_64-debug'
    vstsPackageVersion: '7.0.1'
    
- bash: | 
    unzip llvm-windows_vs17-x86_64-debug-7.0.1.zip
    